# Generated by Django 4.2.7 on 2025-08-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_for', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Initialize', 'Initialize'), ('Approved', 'Approved'), ('Expired', 'Expired')], default='Initialize', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP Model',
                'verbose_name_plural': 'OTP Models',
                'db_table': 'otp_model',
            },
        ),
    ]
